# Generated by Django 4.1.2 on 2022-10-09 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EnvironmentalActivity",
            fields=[
                ("ea_id", models.IntegerField(primary_key=True, serialize=False)),
                ("ea_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                ("region_id", models.IntegerField(primary_key=True, serialize=False)),
                ("region_name", models.CharField(max_length=30)),
                ("latitude", models.IntegerField()),
                ("longitude", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Datapoint",
            fields=[
                ("dp_id", models.IntegerField(primary_key=True, serialize=False)),
                ("dp_datetime", models.DateTimeField()),
                ("is_future", models.BooleanField()),
                ("value", models.FloatField()),
                (
                    "ea_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="arg.environmentalactivity",
                    ),
                ),
                (
                    "region_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="arg.region"
                    ),
                ),
            ],
        ),
    ]
