# Generated by Django 4.1.2 on 2022-11-04 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EnvironmentalActivity",
            fields=[
                (
                    "ea_name",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "region_name",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("latitude", models.IntegerField(default=0)),
                ("longitude", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="UntrackedRegion",
            fields=[
                (
                    "untrackedregion_name",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubRegion",
            fields=[
                (
                    "subregion_name",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="arg.region"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Datapoint",
            fields=[
                ("dp_id", models.AutoField(primary_key=True, serialize=False)),
                ("dp_datetime", models.DateTimeField()),
                ("is_future", models.BooleanField()),
                ("value", models.FloatField()),
                (
                    "ea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="arg.environmentalactivity",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="arg.region"
                    ),
                ),
            ],
        ),
    ]
