# Generated by Django 4.1.2 on 2022-10-13 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubRegion',
            fields=[
                ('subregion_id', models.IntegerField(primary_key=True, serialize=False)),
                ('subregion_name', models.CharField(max_length=50)),
                ('region_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arg.region')),
            ],
        ),
    ]
