# Generated by Django 4.1.2 on 2022-11-18 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subregion',
            name='region',
        ),
        migrations.DeleteModel(
            name='UntrackedRegion',
        ),
        migrations.DeleteModel(
            name='SubRegion',
        ),
    ]
