# Generated by Django 4.1.2 on 2022-10-13 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='region',
            name='longitude',
        ),
    ]
