# Generated by Django 4.1.2 on 2022-10-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arg', '0002_subregion'),
    ]

    operations = [
        migrations.CreateModel(
            name='UntrackedRegion',
            fields=[
                ('untrackedregion_id', models.IntegerField(primary_key=True, serialize=False)),
                ('untrackedregion_name', models.CharField(max_length=50)),
            ],
        ),
    ]
