# Generated by Django 4.1.2 on 2022-11-21 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arg', '0002_remove_subregion_region_delete_untrackedregion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.CharField(max_length=320, primary_key=True, serialize=False)),
                ('hashed_password', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('threshold', models.FloatField()),
                ('ea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arg.environmentalactivity')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arg.user')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arg.region')),
            ],
        ),
    ]
