# Generated by Django 4.1.2 on 2022-10-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arg', '0002_remove_region_latitude_remove_region_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='latitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='region',
            name='longitude',
            field=models.IntegerField(default=0),
        ),
    ]
