# Generated by Django 4.1.2 on 2022-11-03 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arg', '0003_region_latitude_region_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='value',
            field=models.FloatField(null=True),
        ),
    ]
